# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/hwy/bighomework/testneural0504/OOP_assignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/hwy/bighomework/testneural0504/OOP_assignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/hwy/bighomework/testneural0504/OOP_assignment/CMakeFiles /mnt/d/hwy/bighomework/testneural0504/OOP_assignment/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/hwy/bighomework/testneural0504/OOP_assignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

CreateFunc.o: CreateFunc.cpp.o

.PHONY : CreateFunc.o

# target to build an object file
CreateFunc.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CreateFunc.cpp.o
.PHONY : CreateFunc.cpp.o

CreateFunc.i: CreateFunc.cpp.i

.PHONY : CreateFunc.i

# target to preprocess a source file
CreateFunc.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CreateFunc.cpp.i
.PHONY : CreateFunc.cpp.i

CreateFunc.s: CreateFunc.cpp.s

.PHONY : CreateFunc.s

# target to generate assembly for a file
CreateFunc.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CreateFunc.cpp.s
.PHONY : CreateFunc.cpp.s

GraphCompute.o: GraphCompute.cpp.o

.PHONY : GraphCompute.o

# target to build an object file
GraphCompute.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GraphCompute.cpp.o
.PHONY : GraphCompute.cpp.o

GraphCompute.i: GraphCompute.cpp.i

.PHONY : GraphCompute.i

# target to preprocess a source file
GraphCompute.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GraphCompute.cpp.i
.PHONY : GraphCompute.cpp.i

GraphCompute.s: GraphCompute.cpp.s

.PHONY : GraphCompute.s

# target to generate assembly for a file
GraphCompute.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/GraphCompute.cpp.s
.PHONY : GraphCompute.cpp.s

Layer/Dense.o: Layer/Dense.cpp.o

.PHONY : Layer/Dense.o

# target to build an object file
Layer/Dense.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/Dense.cpp.o
.PHONY : Layer/Dense.cpp.o

Layer/Dense.i: Layer/Dense.cpp.i

.PHONY : Layer/Dense.i

# target to preprocess a source file
Layer/Dense.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/Dense.cpp.i
.PHONY : Layer/Dense.cpp.i

Layer/Dense.s: Layer/Dense.cpp.s

.PHONY : Layer/Dense.s

# target to generate assembly for a file
Layer/Dense.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/Dense.cpp.s
.PHONY : Layer/Dense.cpp.s

Layer/Input.o: Layer/Input.cpp.o

.PHONY : Layer/Input.o

# target to build an object file
Layer/Input.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/Input.cpp.o
.PHONY : Layer/Input.cpp.o

Layer/Input.i: Layer/Input.cpp.i

.PHONY : Layer/Input.i

# target to preprocess a source file
Layer/Input.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/Input.cpp.i
.PHONY : Layer/Input.cpp.i

Layer/Input.s: Layer/Input.cpp.s

.PHONY : Layer/Input.s

# target to generate assembly for a file
Layer/Input.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/Input.cpp.s
.PHONY : Layer/Input.cpp.s

Layer/layer.o: Layer/layer.cpp.o

.PHONY : Layer/layer.o

# target to build an object file
Layer/layer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/layer.cpp.o
.PHONY : Layer/layer.cpp.o

Layer/layer.i: Layer/layer.cpp.i

.PHONY : Layer/layer.i

# target to preprocess a source file
Layer/layer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/layer.cpp.i
.PHONY : Layer/layer.cpp.i

Layer/layer.s: Layer/layer.cpp.s

.PHONY : Layer/layer.s

# target to generate assembly for a file
Layer/layer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Layer/layer.cpp.s
.PHONY : Layer/layer.cpp.s

Neural_network.o: Neural_network.cpp.o

.PHONY : Neural_network.o

# target to build an object file
Neural_network.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Neural_network.cpp.o
.PHONY : Neural_network.cpp.o

Neural_network.i: Neural_network.cpp.i

.PHONY : Neural_network.i

# target to preprocess a source file
Neural_network.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Neural_network.cpp.i
.PHONY : Neural_network.cpp.i

Neural_network.s: Neural_network.cpp.s

.PHONY : Neural_network.s

# target to generate assembly for a file
Neural_network.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Neural_network.cpp.s
.PHONY : Neural_network.cpp.s

Operator_0/MyConst.o: Operator_0/MyConst.cpp.o

.PHONY : Operator_0/MyConst.o

# target to build an object file
Operator_0/MyConst.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyConst.cpp.o
.PHONY : Operator_0/MyConst.cpp.o

Operator_0/MyConst.i: Operator_0/MyConst.cpp.i

.PHONY : Operator_0/MyConst.i

# target to preprocess a source file
Operator_0/MyConst.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyConst.cpp.i
.PHONY : Operator_0/MyConst.cpp.i

Operator_0/MyConst.s: Operator_0/MyConst.cpp.s

.PHONY : Operator_0/MyConst.s

# target to generate assembly for a file
Operator_0/MyConst.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyConst.cpp.s
.PHONY : Operator_0/MyConst.cpp.s

Operator_0/MyPlaceholder.o: Operator_0/MyPlaceholder.cpp.o

.PHONY : Operator_0/MyPlaceholder.o

# target to build an object file
Operator_0/MyPlaceholder.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyPlaceholder.cpp.o
.PHONY : Operator_0/MyPlaceholder.cpp.o

Operator_0/MyPlaceholder.i: Operator_0/MyPlaceholder.cpp.i

.PHONY : Operator_0/MyPlaceholder.i

# target to preprocess a source file
Operator_0/MyPlaceholder.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyPlaceholder.cpp.i
.PHONY : Operator_0/MyPlaceholder.cpp.i

Operator_0/MyPlaceholder.s: Operator_0/MyPlaceholder.cpp.s

.PHONY : Operator_0/MyPlaceholder.s

# target to generate assembly for a file
Operator_0/MyPlaceholder.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyPlaceholder.cpp.s
.PHONY : Operator_0/MyPlaceholder.cpp.s

Operator_0/MyVar.o: Operator_0/MyVar.cpp.o

.PHONY : Operator_0/MyVar.o

# target to build an object file
Operator_0/MyVar.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyVar.cpp.o
.PHONY : Operator_0/MyVar.cpp.o

Operator_0/MyVar.i: Operator_0/MyVar.cpp.i

.PHONY : Operator_0/MyVar.i

# target to preprocess a source file
Operator_0/MyVar.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyVar.cpp.i
.PHONY : Operator_0/MyVar.cpp.i

Operator_0/MyVar.s: Operator_0/MyVar.cpp.s

.PHONY : Operator_0/MyVar.s

# target to generate assembly for a file
Operator_0/MyVar.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/MyVar.cpp.s
.PHONY : Operator_0/MyVar.cpp.s

Operator_0/Operator_0.o: Operator_0/Operator_0.cpp.o

.PHONY : Operator_0/Operator_0.o

# target to build an object file
Operator_0/Operator_0.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/Operator_0.cpp.o
.PHONY : Operator_0/Operator_0.cpp.o

Operator_0/Operator_0.i: Operator_0/Operator_0.cpp.i

.PHONY : Operator_0/Operator_0.i

# target to preprocess a source file
Operator_0/Operator_0.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/Operator_0.cpp.i
.PHONY : Operator_0/Operator_0.cpp.i

Operator_0/Operator_0.s: Operator_0/Operator_0.cpp.s

.PHONY : Operator_0/Operator_0.s

# target to generate assembly for a file
Operator_0/Operator_0.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_0/Operator_0.cpp.s
.PHONY : Operator_0/Operator_0.cpp.s

Operator_1/myexp.o: Operator_1/myexp.cpp.o

.PHONY : Operator_1/myexp.o

# target to build an object file
Operator_1/myexp.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/myexp.cpp.o
.PHONY : Operator_1/myexp.cpp.o

Operator_1/myexp.i: Operator_1/myexp.cpp.i

.PHONY : Operator_1/myexp.i

# target to preprocess a source file
Operator_1/myexp.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/myexp.cpp.i
.PHONY : Operator_1/myexp.cpp.i

Operator_1/myexp.s: Operator_1/myexp.cpp.s

.PHONY : Operator_1/myexp.s

# target to generate assembly for a file
Operator_1/myexp.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/myexp.cpp.s
.PHONY : Operator_1/myexp.cpp.s

Operator_1/mylog.o: Operator_1/mylog.cpp.o

.PHONY : Operator_1/mylog.o

# target to build an object file
Operator_1/mylog.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mylog.cpp.o
.PHONY : Operator_1/mylog.cpp.o

Operator_1/mylog.i: Operator_1/mylog.cpp.i

.PHONY : Operator_1/mylog.i

# target to preprocess a source file
Operator_1/mylog.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mylog.cpp.i
.PHONY : Operator_1/mylog.cpp.i

Operator_1/mylog.s: Operator_1/mylog.cpp.s

.PHONY : Operator_1/mylog.s

# target to generate assembly for a file
Operator_1/mylog.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mylog.cpp.s
.PHONY : Operator_1/mylog.cpp.s

Operator_1/myprint.o: Operator_1/myprint.cpp.o

.PHONY : Operator_1/myprint.o

# target to build an object file
Operator_1/myprint.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/myprint.cpp.o
.PHONY : Operator_1/myprint.cpp.o

Operator_1/myprint.i: Operator_1/myprint.cpp.i

.PHONY : Operator_1/myprint.i

# target to preprocess a source file
Operator_1/myprint.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/myprint.cpp.i
.PHONY : Operator_1/myprint.cpp.i

Operator_1/myprint.s: Operator_1/myprint.cpp.s

.PHONY : Operator_1/myprint.s

# target to generate assembly for a file
Operator_1/myprint.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/myprint.cpp.s
.PHONY : Operator_1/myprint.cpp.s

Operator_1/mysigmoid.o: Operator_1/mysigmoid.cpp.o

.PHONY : Operator_1/mysigmoid.o

# target to build an object file
Operator_1/mysigmoid.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mysigmoid.cpp.o
.PHONY : Operator_1/mysigmoid.cpp.o

Operator_1/mysigmoid.i: Operator_1/mysigmoid.cpp.i

.PHONY : Operator_1/mysigmoid.i

# target to preprocess a source file
Operator_1/mysigmoid.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mysigmoid.cpp.i
.PHONY : Operator_1/mysigmoid.cpp.i

Operator_1/mysigmoid.s: Operator_1/mysigmoid.cpp.s

.PHONY : Operator_1/mysigmoid.s

# target to generate assembly for a file
Operator_1/mysigmoid.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mysigmoid.cpp.s
.PHONY : Operator_1/mysigmoid.cpp.s

Operator_1/mysin.o: Operator_1/mysin.cpp.o

.PHONY : Operator_1/mysin.o

# target to build an object file
Operator_1/mysin.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mysin.cpp.o
.PHONY : Operator_1/mysin.cpp.o

Operator_1/mysin.i: Operator_1/mysin.cpp.i

.PHONY : Operator_1/mysin.i

# target to preprocess a source file
Operator_1/mysin.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mysin.cpp.i
.PHONY : Operator_1/mysin.cpp.i

Operator_1/mysin.s: Operator_1/mysin.cpp.s

.PHONY : Operator_1/mysin.s

# target to generate assembly for a file
Operator_1/mysin.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mysin.cpp.s
.PHONY : Operator_1/mysin.cpp.s

Operator_1/mytanh.o: Operator_1/mytanh.cpp.o

.PHONY : Operator_1/mytanh.o

# target to build an object file
Operator_1/mytanh.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mytanh.cpp.o
.PHONY : Operator_1/mytanh.cpp.o

Operator_1/mytanh.i: Operator_1/mytanh.cpp.i

.PHONY : Operator_1/mytanh.i

# target to preprocess a source file
Operator_1/mytanh.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mytanh.cpp.i
.PHONY : Operator_1/mytanh.cpp.i

Operator_1/mytanh.s: Operator_1/mytanh.cpp.s

.PHONY : Operator_1/mytanh.s

# target to generate assembly for a file
Operator_1/mytanh.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/mytanh.cpp.s
.PHONY : Operator_1/mytanh.cpp.s

Operator_1/operator_1.o: Operator_1/operator_1.cpp.o

.PHONY : Operator_1/operator_1.o

# target to build an object file
Operator_1/operator_1.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/operator_1.cpp.o
.PHONY : Operator_1/operator_1.cpp.o

Operator_1/operator_1.i: Operator_1/operator_1.cpp.i

.PHONY : Operator_1/operator_1.i

# target to preprocess a source file
Operator_1/operator_1.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/operator_1.cpp.i
.PHONY : Operator_1/operator_1.cpp.i

Operator_1/operator_1.s: Operator_1/operator_1.cpp.s

.PHONY : Operator_1/operator_1.s

# target to generate assembly for a file
Operator_1/operator_1.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_1/operator_1.cpp.s
.PHONY : Operator_1/operator_1.cpp.s

Operator_2/mydiv.o: Operator_2/mydiv.cpp.o

.PHONY : Operator_2/mydiv.o

# target to build an object file
Operator_2/mydiv.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mydiv.cpp.o
.PHONY : Operator_2/mydiv.cpp.o

Operator_2/mydiv.i: Operator_2/mydiv.cpp.i

.PHONY : Operator_2/mydiv.i

# target to preprocess a source file
Operator_2/mydiv.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mydiv.cpp.i
.PHONY : Operator_2/mydiv.cpp.i

Operator_2/mydiv.s: Operator_2/mydiv.cpp.s

.PHONY : Operator_2/mydiv.s

# target to generate assembly for a file
Operator_2/mydiv.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mydiv.cpp.s
.PHONY : Operator_2/mydiv.cpp.s

Operator_2/myequal.o: Operator_2/myequal.cpp.o

.PHONY : Operator_2/myequal.o

# target to build an object file
Operator_2/myequal.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myequal.cpp.o
.PHONY : Operator_2/myequal.cpp.o

Operator_2/myequal.i: Operator_2/myequal.cpp.i

.PHONY : Operator_2/myequal.i

# target to preprocess a source file
Operator_2/myequal.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myequal.cpp.i
.PHONY : Operator_2/myequal.cpp.i

Operator_2/myequal.s: Operator_2/myequal.cpp.s

.PHONY : Operator_2/myequal.s

# target to generate assembly for a file
Operator_2/myequal.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myequal.cpp.s
.PHONY : Operator_2/myequal.cpp.s

Operator_2/mygreater.o: Operator_2/mygreater.cpp.o

.PHONY : Operator_2/mygreater.o

# target to build an object file
Operator_2/mygreater.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mygreater.cpp.o
.PHONY : Operator_2/mygreater.cpp.o

Operator_2/mygreater.i: Operator_2/mygreater.cpp.i

.PHONY : Operator_2/mygreater.i

# target to preprocess a source file
Operator_2/mygreater.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mygreater.cpp.i
.PHONY : Operator_2/mygreater.cpp.i

Operator_2/mygreater.s: Operator_2/mygreater.cpp.s

.PHONY : Operator_2/mygreater.s

# target to generate assembly for a file
Operator_2/mygreater.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mygreater.cpp.s
.PHONY : Operator_2/mygreater.cpp.s

Operator_2/mygreaterequal.o: Operator_2/mygreaterequal.cpp.o

.PHONY : Operator_2/mygreaterequal.o

# target to build an object file
Operator_2/mygreaterequal.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mygreaterequal.cpp.o
.PHONY : Operator_2/mygreaterequal.cpp.o

Operator_2/mygreaterequal.i: Operator_2/mygreaterequal.cpp.i

.PHONY : Operator_2/mygreaterequal.i

# target to preprocess a source file
Operator_2/mygreaterequal.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mygreaterequal.cpp.i
.PHONY : Operator_2/mygreaterequal.cpp.i

Operator_2/mygreaterequal.s: Operator_2/mygreaterequal.cpp.s

.PHONY : Operator_2/mygreaterequal.s

# target to generate assembly for a file
Operator_2/mygreaterequal.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mygreaterequal.cpp.s
.PHONY : Operator_2/mygreaterequal.cpp.s

Operator_2/myless.o: Operator_2/myless.cpp.o

.PHONY : Operator_2/myless.o

# target to build an object file
Operator_2/myless.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myless.cpp.o
.PHONY : Operator_2/myless.cpp.o

Operator_2/myless.i: Operator_2/myless.cpp.i

.PHONY : Operator_2/myless.i

# target to preprocess a source file
Operator_2/myless.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myless.cpp.i
.PHONY : Operator_2/myless.cpp.i

Operator_2/myless.s: Operator_2/myless.cpp.s

.PHONY : Operator_2/myless.s

# target to generate assembly for a file
Operator_2/myless.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myless.cpp.s
.PHONY : Operator_2/myless.cpp.s

Operator_2/mylessequal.o: Operator_2/mylessequal.cpp.o

.PHONY : Operator_2/mylessequal.o

# target to build an object file
Operator_2/mylessequal.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mylessequal.cpp.o
.PHONY : Operator_2/mylessequal.cpp.o

Operator_2/mylessequal.i: Operator_2/mylessequal.cpp.i

.PHONY : Operator_2/mylessequal.i

# target to preprocess a source file
Operator_2/mylessequal.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mylessequal.cpp.i
.PHONY : Operator_2/mylessequal.cpp.i

Operator_2/mylessequal.s: Operator_2/mylessequal.cpp.s

.PHONY : Operator_2/mylessequal.s

# target to generate assembly for a file
Operator_2/mylessequal.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mylessequal.cpp.s
.PHONY : Operator_2/mylessequal.cpp.s

Operator_2/myminus.o: Operator_2/myminus.cpp.o

.PHONY : Operator_2/myminus.o

# target to build an object file
Operator_2/myminus.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myminus.cpp.o
.PHONY : Operator_2/myminus.cpp.o

Operator_2/myminus.i: Operator_2/myminus.cpp.i

.PHONY : Operator_2/myminus.i

# target to preprocess a source file
Operator_2/myminus.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myminus.cpp.i
.PHONY : Operator_2/myminus.cpp.i

Operator_2/myminus.s: Operator_2/myminus.cpp.s

.PHONY : Operator_2/myminus.s

# target to generate assembly for a file
Operator_2/myminus.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myminus.cpp.s
.PHONY : Operator_2/myminus.cpp.s

Operator_2/mymul.o: Operator_2/mymul.cpp.o

.PHONY : Operator_2/mymul.o

# target to build an object file
Operator_2/mymul.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mymul.cpp.o
.PHONY : Operator_2/mymul.cpp.o

Operator_2/mymul.i: Operator_2/mymul.cpp.i

.PHONY : Operator_2/mymul.i

# target to preprocess a source file
Operator_2/mymul.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mymul.cpp.i
.PHONY : Operator_2/mymul.cpp.i

Operator_2/mymul.s: Operator_2/mymul.cpp.s

.PHONY : Operator_2/mymul.s

# target to generate assembly for a file
Operator_2/mymul.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/mymul.cpp.s
.PHONY : Operator_2/mymul.cpp.s

Operator_2/myplus.o: Operator_2/myplus.cpp.o

.PHONY : Operator_2/myplus.o

# target to build an object file
Operator_2/myplus.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myplus.cpp.o
.PHONY : Operator_2/myplus.cpp.o

Operator_2/myplus.i: Operator_2/myplus.cpp.i

.PHONY : Operator_2/myplus.i

# target to preprocess a source file
Operator_2/myplus.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myplus.cpp.i
.PHONY : Operator_2/myplus.cpp.i

Operator_2/myplus.s: Operator_2/myplus.cpp.s

.PHONY : Operator_2/myplus.s

# target to generate assembly for a file
Operator_2/myplus.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/myplus.cpp.s
.PHONY : Operator_2/myplus.cpp.s

Operator_2/operator_2.o: Operator_2/operator_2.cpp.o

.PHONY : Operator_2/operator_2.o

# target to build an object file
Operator_2/operator_2.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/operator_2.cpp.o
.PHONY : Operator_2/operator_2.cpp.o

Operator_2/operator_2.i: Operator_2/operator_2.cpp.i

.PHONY : Operator_2/operator_2.i

# target to preprocess a source file
Operator_2/operator_2.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/operator_2.cpp.i
.PHONY : Operator_2/operator_2.cpp.i

Operator_2/operator_2.s: Operator_2/operator_2.cpp.s

.PHONY : Operator_2/operator_2.s

# target to generate assembly for a file
Operator_2/operator_2.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_2/operator_2.cpp.s
.PHONY : Operator_2/operator_2.cpp.s

Operator_3/MyCond.o: Operator_3/MyCond.cpp.o

.PHONY : Operator_3/MyCond.o

# target to build an object file
Operator_3/MyCond.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_3/MyCond.cpp.o
.PHONY : Operator_3/MyCond.cpp.o

Operator_3/MyCond.i: Operator_3/MyCond.cpp.i

.PHONY : Operator_3/MyCond.i

# target to preprocess a source file
Operator_3/MyCond.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_3/MyCond.cpp.i
.PHONY : Operator_3/MyCond.cpp.i

Operator_3/MyCond.s: Operator_3/MyCond.cpp.s

.PHONY : Operator_3/MyCond.s

# target to generate assembly for a file
Operator_3/MyCond.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_3/MyCond.cpp.s
.PHONY : Operator_3/MyCond.cpp.s

Operator_3/Operator_3.o: Operator_3/Operator_3.cpp.o

.PHONY : Operator_3/Operator_3.o

# target to build an object file
Operator_3/Operator_3.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_3/Operator_3.cpp.o
.PHONY : Operator_3/Operator_3.cpp.o

Operator_3/Operator_3.i: Operator_3/Operator_3.cpp.i

.PHONY : Operator_3/Operator_3.i

# target to preprocess a source file
Operator_3/Operator_3.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_3/Operator_3.cpp.i
.PHONY : Operator_3/Operator_3.cpp.i

Operator_3/Operator_3.s: Operator_3/Operator_3.cpp.s

.PHONY : Operator_3/Operator_3.s

# target to generate assembly for a file
Operator_3/Operator_3.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Operator_3/Operator_3.cpp.s
.PHONY : Operator_3/Operator_3.cpp.s

Storage.o: Storage.cpp.o

.PHONY : Storage.o

# target to build an object file
Storage.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Storage.cpp.o
.PHONY : Storage.cpp.o

Storage.i: Storage.cpp.i

.PHONY : Storage.i

# target to preprocess a source file
Storage.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Storage.cpp.i
.PHONY : Storage.cpp.i

Storage.s: Storage.cpp.s

.PHONY : Storage.s

# target to generate assembly for a file
Storage.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Storage.cpp.s
.PHONY : Storage.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

test_minst.o: test_minst.cpp.o

.PHONY : test_minst.o

# target to build an object file
test_minst.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test_minst.cpp.o
.PHONY : test_minst.cpp.o

test_minst.i: test_minst.cpp.i

.PHONY : test_minst.i

# target to preprocess a source file
test_minst.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test_minst.cpp.i
.PHONY : test_minst.cpp.i

test_minst.s: test_minst.cpp.s

.PHONY : test_minst.s

# target to generate assembly for a file
test_minst.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/test_minst.cpp.s
.PHONY : test_minst.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... CreateFunc.o"
	@echo "... CreateFunc.i"
	@echo "... CreateFunc.s"
	@echo "... GraphCompute.o"
	@echo "... GraphCompute.i"
	@echo "... GraphCompute.s"
	@echo "... Layer/Dense.o"
	@echo "... Layer/Dense.i"
	@echo "... Layer/Dense.s"
	@echo "... Layer/Input.o"
	@echo "... Layer/Input.i"
	@echo "... Layer/Input.s"
	@echo "... Layer/layer.o"
	@echo "... Layer/layer.i"
	@echo "... Layer/layer.s"
	@echo "... Neural_network.o"
	@echo "... Neural_network.i"
	@echo "... Neural_network.s"
	@echo "... Operator_0/MyConst.o"
	@echo "... Operator_0/MyConst.i"
	@echo "... Operator_0/MyConst.s"
	@echo "... Operator_0/MyPlaceholder.o"
	@echo "... Operator_0/MyPlaceholder.i"
	@echo "... Operator_0/MyPlaceholder.s"
	@echo "... Operator_0/MyVar.o"
	@echo "... Operator_0/MyVar.i"
	@echo "... Operator_0/MyVar.s"
	@echo "... Operator_0/Operator_0.o"
	@echo "... Operator_0/Operator_0.i"
	@echo "... Operator_0/Operator_0.s"
	@echo "... Operator_1/myexp.o"
	@echo "... Operator_1/myexp.i"
	@echo "... Operator_1/myexp.s"
	@echo "... Operator_1/mylog.o"
	@echo "... Operator_1/mylog.i"
	@echo "... Operator_1/mylog.s"
	@echo "... Operator_1/myprint.o"
	@echo "... Operator_1/myprint.i"
	@echo "... Operator_1/myprint.s"
	@echo "... Operator_1/mysigmoid.o"
	@echo "... Operator_1/mysigmoid.i"
	@echo "... Operator_1/mysigmoid.s"
	@echo "... Operator_1/mysin.o"
	@echo "... Operator_1/mysin.i"
	@echo "... Operator_1/mysin.s"
	@echo "... Operator_1/mytanh.o"
	@echo "... Operator_1/mytanh.i"
	@echo "... Operator_1/mytanh.s"
	@echo "... Operator_1/operator_1.o"
	@echo "... Operator_1/operator_1.i"
	@echo "... Operator_1/operator_1.s"
	@echo "... Operator_2/mydiv.o"
	@echo "... Operator_2/mydiv.i"
	@echo "... Operator_2/mydiv.s"
	@echo "... Operator_2/myequal.o"
	@echo "... Operator_2/myequal.i"
	@echo "... Operator_2/myequal.s"
	@echo "... Operator_2/mygreater.o"
	@echo "... Operator_2/mygreater.i"
	@echo "... Operator_2/mygreater.s"
	@echo "... Operator_2/mygreaterequal.o"
	@echo "... Operator_2/mygreaterequal.i"
	@echo "... Operator_2/mygreaterequal.s"
	@echo "... Operator_2/myless.o"
	@echo "... Operator_2/myless.i"
	@echo "... Operator_2/myless.s"
	@echo "... Operator_2/mylessequal.o"
	@echo "... Operator_2/mylessequal.i"
	@echo "... Operator_2/mylessequal.s"
	@echo "... Operator_2/myminus.o"
	@echo "... Operator_2/myminus.i"
	@echo "... Operator_2/myminus.s"
	@echo "... Operator_2/mymul.o"
	@echo "... Operator_2/mymul.i"
	@echo "... Operator_2/mymul.s"
	@echo "... Operator_2/myplus.o"
	@echo "... Operator_2/myplus.i"
	@echo "... Operator_2/myplus.s"
	@echo "... Operator_2/operator_2.o"
	@echo "... Operator_2/operator_2.i"
	@echo "... Operator_2/operator_2.s"
	@echo "... Operator_3/MyCond.o"
	@echo "... Operator_3/MyCond.i"
	@echo "... Operator_3/MyCond.s"
	@echo "... Operator_3/Operator_3.o"
	@echo "... Operator_3/Operator_3.i"
	@echo "... Operator_3/Operator_3.s"
	@echo "... Storage.o"
	@echo "... Storage.i"
	@echo "... Storage.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_minst.o"
	@echo "... test_minst.i"
	@echo "... test_minst.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

